# Generated by Django 4.2.5 on 2023-11-03 12:04

import django.contrib.auth.password_validation
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=128, unique=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password])),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
