# Generated by Django 4.2.5 on 2023-10-02 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default=None, max_length=128, unique=True)),
                ('email_verified_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_number', models.IntegerField(blank=True, default=None, unique=True)),
                ('mobile_number_verified_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-time_stamp'],
            },
        ),
    ]
